### ISSUE TITLE
Refactor deprecated `setModalLoader();` usage

### ISSUE THREAD

**Issue by luke-** [humhub/updater#34]

**Comment by yurabakhtin** [comment]
@luke- Core PR https://github.com/humhub/humhub/pull/6389 - I have removed the deprecated JS function and implemented one new `humhub.require("ui.modal").footerLoader()` instead.

Then I have updated this module in the PR https://github.com/humhub/updater/pull/35, but it requires new HumHub vesion 1.15, if it is not ok, I can try to update the JS code without using the new JS function `footerLoader()`.

**Comment by luke-** [comment]
@yurabakhtin The footer loader of the updater is very special. Do you think its useful to provide a separate `footerLoader()` in the core, which is only used by the updater?

Wouldn't it be better to implement such a loader only in the updater?

Then we would not have problems with version dependencies.

**Comment by luke-** [comment]
@yurabakhtin Sorry, missed that in my review. If the `footerLoader();` is also used in the core, your approach is fine.

**Comment by luke-** [comment]
@yurabakhtin FYI, I've added the core change in the new migration doc: https://github.com/humhub/humhub/pull/6389/commits/a2e708f274161c792cbffd951dfd68ef43ef1268 - Please also add changes here.

**Comment by yurabakhtin** [comment]
@luke- 

> FYI, I've added the core change in the new migration doc: [humhub/humhub@a2e708f](https://github.com/humhub/humhub/commit/a2e708f274161c792cbffd951dfd68ef43ef1268) - Please also add changes here.

Do you mean to update the line `Removed deprecated javascript method setModalLoader()` somehow, or is it info for me to update the file in future when I will do some similar changes?

**Comment by yurabakhtin** [comment]
> Yes, I can implement/copy the same JS code from `humhub.require("ui.modal").footerLoader()` to this module `updater`, so we can revert the min version to `1.0` as it was before. Should I do this?

Should I do something with this module "Updater" in order to don't increase the min version to 1.15?

**Comment by luke-** [comment]
> @luke-
> 
> > FYI, I've added the core change in the new migration doc: [humhub/humhub@a2e708f](https://github.com/humhub/humhub/commit/a2e708f274161c792cbffd951dfd68ef43ef1268) - Please also add changes here.
> 
> Do you mean to update the line `Removed deprecated javascript method setModalLoader()` somehow, or is it info for me to update the file in future when I will do some similar changes?

It's just a info for you, for future similar changes.

**Comment by luke-** [comment]
> > Yes, I can implement/copy the same JS code from `humhub.require("ui.modal").footerLoader()` to this module `updater`, so we can revert the min version to `1.0` as it was before. Should I do this?
> 
> @luke- Should I do something with this module "Updater" in order to don't increase the min version to 1.15?

No, it's fine, I'll merge the PR. Thanks
