### ISSUE TITLE
On error, hide loader and do not interrupt warning

### ISSUE THREAD

**Issue by luke-** [humhub/updater#44]
If an error occurs, the loader and warning should no longer be displayed. 

![image](https://github.com/humhub/updater/assets/4736168/b581e213-c1fd-44c6-b8e6-7d1aedde8c2a)

**Comment by luke-** [comment]
Related: https://community.humhub.com/comment/perma?id=47372

**Comment by yurabakhtin** [comment]
@luke- Fixed in commit https://github.com/humhub/updater/pull/46.
